### PR TITLE
[nativelib] Implement List#pop, List#shift, List#unshift

### PR DESCRIPTION
**Pull request by bmulvihill**
- Implements List#pop to pop last element from a list.
- Implements List#shift, List#unshift, to remove/add from front of list
- Returns list if no value provide for `push`, `shift`

### CODE REVIEW

**Comment by faultyserver** [comment]
LGTM! Great stuff :)

**Comment by minirop** [comment]
just curious, are they cases where calling `shift` or `push` without arguments are useful/necessary?

**Comment by bmulvihill** [comment]
Probably not, I was originally going to raise an error but decided to follow Ruby behavior.

**Comment by faultyserver** [comment]
With the way that native lib methods are currently implemented, I think passively supporting a no-argument version is easiest. Since native methods just accept an array of arguments and extract them manually, it's not really possible to have the truly nice behavior of not matching the function clause if no arguments are provided.

#44 was made to address a similar concern with using `*` both for multiplication and as a unary splat, but I ended up closing the issue because it's generally not a necessity, but if it ever does get implemented, restricting the method to only match when given an argument would make more sense to me.

Maybe a better solution than having multiple native clauses would be providing a nice way of saying "this native clause doesn't match" so that the stdlib can also provide clauses for the same function (right now, the native clause will always match, so functors can't be extended in the stdlib :/)

**Pull request merged**
