### PR TITLE
Implement List#-, List#<, List#<=

### PR DESCRIPTION
**Pull request by bmulvihill**
Related https://github.com/myst-lang/myst/issues/57

Side note: I noticed when naming the List specs `List#<` or `List#<=` it was causing the specs to hang. I haven't had a chance to look into it.

### CODE REVIEW

**Review by faultyserver — COMMENTED** [review]
Looks really good! Sorry I couldn't review this quicker.

One thing that'd be good to test, though, is that `List#<` and `List#<=` work for Lists with different orderings.

For example, I would expect `[3, 1] < [1, 2, 3]` to return true. Even though the elements are in different orders, the left is still a proper subset of the right.

I think your implementation will already handle this appropriately, but having tests around it would be really good for complete coverage of the semantics.

Thanks :)

**Comment by faultyserver** [comment]
For the side note: I mentioned in [the discord](http://discord.myst-lang.org/) that my best guess for the hang is a parser or lexer bug, something to do with expecting a string interpolation. I haven't had a chance to try to reproduce this yet, though. I would appreciate if someone could file an issue for it so it doesn't get forgotten.

**Comment by bmulvihill** [comment]
@faultyserver Added some additional specs

**Comment by faultyserver** [comment]
Awesome, thanks for adding those :)

**Pull request merged**
